#!/bin/sh
# EasyStick udhcpc hook to update status.txt on IP assignment or renewal
# NOMMU-safe: zero subshells, zero pipes to prevent vfork issues in ash

ACTION="$1"

case "$ACTION" in
	bound|renew)
		_ssid="none"
		if [ -f /tmp/wpa_supplicant.conf ]; then
			while IFS= read -r line; do
				case "$line" in
					*ssid=*|*ssid\ =*)
						_ssid="${line#*\"}"
						_ssid="${_ssid%\"*}"
						break
						;;
				esac
			done < /tmp/wpa_supplicant.conf
		fi
		[ -x /usr/sbin/easystick-update-status ] && /usr/sbin/easystick-update-status "CONNECTED" "$ip" "$subnet" "$router" "$_ssid" "sta"
		;;
	deconfig|leasefail)
		[ -x /usr/sbin/easystick-update-status ] && /usr/sbin/easystick-update-status "DISCONNECTED" "none" "none" "none" "none" "sta"
		;;
esac

exit 0
